import Head from "next/head";
import { Inter } from "@next/font/google";
import { useSession, useSupabaseClient } from "@supabase/auth-helpers-react";
import Authentication from "@/components/Index/Authentication";
import Main from "@/components/Index/Main";
import { AnimatePresence, motion } from "framer-motion";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AnimatePresence>
        <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        >
        <Main />
        </motion.div>
      </AnimatePresence>
    </>
  );
}
