import Head from "next/head";
import { Inter } from "@next/font/google";
import { useSession, useSupabaseClient } from "@supabase/auth-helpers-react";
import Authentication from "@/components/Index/Authentication";
import Main from "@/components/Index/Main";


const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const session: any = useSession();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-[#282A3A] h-screen">
        {!session ? (
          <Authentication />
        ) : (
          <>
            <Main />
          </>
        )}
      </div>
    </>
  );
}
